import './globals.css'
import { Inter } from 'next/font/google'
import ToasterContext from './context/ToasterContext';
import Navbar from '@/components/navbar/Navbar';
import { getCurrentUser } from './actions/getCurrentUser';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const currentUser = await getCurrentUser();
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToasterContext />
        <Navbar currentUser={currentUser}/>
        {children}

      </body>

    </html>
  )
}
